sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=proflewis/geog0111

before_script:
  - version="$(awk '$2 == "GEOG0111_VERSION" { print $3; exit }' Dockerfile)"
  - docker pull "$IMAGE_NAME" || true
script:
  - docker build --pull --tag "$IMAGE_NAME" .
# --cache-from "$IMAGE_NAME"


after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master
